### PR TITLE
BotRequest model

### LINKED ISSUE #698: Messages collection
Log each incoming request, and how Gambit responds.

* `_id`
* `client` -- `'mobilecommons'`
* `client_message_id` -- Mobile Commons `message_id`
* `client_sender_id`-- Mobile Commons `profile_id`
* `client_broadcast_id` -- Mobile Commons `broadcast_id`, set when User is responding to a broadcast message
* `phone`
* `incoming_message`
* `incoming_image_url` -- Media url?
* `response_message_type`
* `response_message`
* `user` -- DS Northstar User ID
* `current_campaign` -- DS Campaign ID we save to User upon sending response

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Takes our Gambit Stathat events for bot messages in #726 a step further by storing them in a new `bot_requests` collection in the Gambit DB.

*  Log incoming POST requests to `/chatbot`, `/donorschoosebot`, and `/signups` along with the Bot response back:
    * `bot` -- The Bot that responded (`campaignbot`, `donorschoosebot`, future Onboarding, SMS Games, Account Management Bots that we need CMS's like Gambit Jr to maintain copy in)
   * `bot_msg_type` -- The type of Bot message we're sending back as a response, e.g. `'ask_zip'`, `'menu_completed'`)
    * `bot_msg` -- The rendered response message to deliver back to the User

* Adds a `client` property to our incoming Express request to determine which body properties to store.

    * `mobilecommons` -- incoming Mobile Commons mData request. If set, we store things like the `broadcast_id`, which is critical for Signup Broadcast Support #651 to gather analytics for how many Users signup from a given Campaign Signup Broadcast (filter by `body.broadcast_id` and `bot_response_type === 'msg_menu_signedup_gambit`)

    * `external-signup`  -- incoming Quicksilver request to trigger the CampaignBot External Signup Confirmation message (`msg_menu_signedup_external`)

#### How should this be reviewed?
1. I could use some second opinions on all names (both of `bot_requests` and all its fields), and exactly what messages we want to store. Am I missing anything?  Do the names make sense?

2. Currently logging all triggered External Signup confirmation messages -- but we sure send thousands and thousands of them. Still, seems like it would be odd not to. It would also help us catch if we happened to send multiple external confirmation messages if there were bugs.

3. I'll deploy to staging, and post around the various endpoints to start populating the table. Please take a look at live staging  `bot_requests` data and confirm 🆗 . Need access to the staging DB? There's [an app for that](https://github.com/DoSomething/ServerConfig/wiki/4.0-Gambit#staging).

#### Relevant tickets
Fixes #698 

#### Checklist
- [x] Tested on staging.

cc @deadlybutter @mshmsh5000 @sheyd

### CODE REVIEW

**Comment by aaronschachter** [comment]
The chatbot and donorschoosebot endpoints are logging the entire request body we receive from Mobile Commons mData's -- and it's a doozy:

screen shot 2016-11-09 at 12 39 21 pm

**Review by sergiitk — APPROVED** [review]

**Comment by aaronschachter** [comment]
This collection is missing a timestamp, @sergii-tkachenko and i decided to add `created_at` -- adding in shortly. Also to avoid logging all 283 `req.body` properties sent with a Mobile Commons mData request.

**Comment by deadlybutter** [comment]
Fun fact, mongo ID's are timestamps! On mobile or I'd link example

**Comment by aaronschachter** [comment]
Thanks for the tip @deadlybutter ! [noted 📝 ](https://docs.mongodb.com/v3.2/reference/method/ObjectId.getTimestamp/)

**Comment by aaronschachter** [comment]
Chatted with @sergii-tkachenko about this branch and updated this branch to only store relevant request body properties from a Mobile Commons request (`keyword`, `args`, `broadcast_id`, etc) instead all 283 properties

**Pull request merged**
