### PR TITLE
Deprecate app.locals.logger

### LINKED ISSUE #848: Use pre-configured winston loggers to avoid memory leaks
Refs https://github.com/DoSomething/gambit/issues/837#issuecomment-292563373

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Updates the Winston package and refactors Gambit to use its preconfigured instance.

#### How should this be reviewed?
Test every endpoint 😬 

#### Any background context you want to provide?
https://github.com/DoSomething/gambit/issues/837#issuecomment-292563373

#### Relevant tickets
Fixes #848 

#### Checklist
- [x] Tested on staging

### CODE REVIEW

**Comment by aaronschachter** [comment]
Getting chatbot responses back, but seeing a `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 259): MongoError: quota exceeded` in our logs on staging.

**Comment by aaronschachter** [comment]
Removed all documents from the `log` collection on staging to avoid

**Comment by sergii-tkachenko** [comment]
This is awesome. On thing: are you sure that you don't need to create logger category, like @rapala61 mentioned in the example: `winston.loggers.get('category')`? Or is it using default category when simply required with `const logger = require('winston');`?

**Comment by aaronschachter** [comment]
Yeah, categories aren't required. This is logging into our `logs` collection and to the console -- we'd want to use categories if we wanted to do something like sending logs of different types to different locations: https://github.com/winstonjs/winston#working-with-multiple-loggers-in-winston

**Review by sergiitk — APPROVED** [review]
🎉

**Pull request merged**
