### PR TITLE
Remove deprecated /yes-no-gateway and /campaign-transition endpoints

### LINKED ISSUE #707: Remove legacy Yes/No and Start Campaign Transition endpoints
Not used at all anymore, these are good to go 🔥 💀 🔪

### PR DESCRIPTION
**Pull request by aaronschachter**
#### What's this PR do?
Gets rid of code and endpoints we no longer use. If an mData posts here, Gambit triggers a 404 -- which will help us quickly find any keywords pointing to old campaigns once triggered

#### How should this be reviewed?
We just need to confirm the regular `/reportback/:campaignName` works as expected -- I will configure the staging legacy Campaign I use to no longer post to these paths and confirm I can still reportback on the legacy endpoint.

#### Any background context you want to provide?
🎶 🎤 I love, killing code. Put another dime in the Github, baby 🎸 

#### Relevant tickets
Fixes #707 

#### Checklist
- [x] Documentation added for new features/changed endpoints.
- [x] Tested on staging.

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
Do you want to drop corresponding tables as well?

**Comment by aaronschachter** [comment]
I sure do -- there's https://github.com/DoSomething/gambit/issues/591 for dropping. I was planning on just dropping manually in the DB with Compose or RoboMongo -- unless there's a better way?

**Comment by sergii-tkachenko** [comment]
Usually in frameworks migrations are pretty useful for that purpose. Here let's stick with Compose or RoboMongo.

**Review by sergiitk — APPROVED** [review]
🔥 👴 🔥

**Pull request merged**
